#!/usr/bin/env python3
"""Analyze whether stage-2 gains concentrate on dense relations and find top-N subsets."""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


DATASETS = [
    "KG20C",
    "codex-m",
    "WN18RR",
    "FB15k-237",
    "codex-l",
    "YAGO3-10",
]

FEATURE_KEYS = [
    "num_triples",
    "num_objects",
    "avg_tails_per_sp",
    "num_rules",
    "num_deps",
    "dep_per_rule",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--wide-summary",
        default="reports/experiment_summary/experiment_summary_wide.csv",
        help="Wide experiment summary CSV generated by summarize_experiment_results.py",
    )
    parser.add_argument(
        "--output-dir",
        default="reports/stage2_gain_subsets",
        help="Directory where subset analysis outputs will be written.",
    )
    return parser.parse_args()


def to_float(value: object) -> Optional[float]:
    if value in ("", None):
        return None
    return float(value)


def fmt_float(value: Optional[float]) -> str:
    return "" if value is None else f"{value:.6f}"


def fmt_ratio(value: Optional[float]) -> str:
    return "" if value is None else f"{value:.3f}x"


def read_wide_summary(path: Path) -> Dict[str, List[Dict[str, str]]]:
    rows_by_dataset: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    with path.open("r", encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            rows_by_dataset[row["dataset"]].append(row)
    return rows_by_dataset


def best_completed_config(rows: Sequence[Dict[str, str]]) -> Dict[str, str]:
    completed = [row for row in rows if row["config_status"] == "done" and row["stage2_mrr"]]
    if not completed:
        raise ValueError("No completed rows found for dataset")
    return max(completed, key=lambda row: float(row["stage2_mrr"]))


def read_json(path: Path) -> Dict[str, object]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def average(rows: Iterable[Dict[str, object]], key: str) -> Optional[float]:
    values = [float(row[key]) for row in rows if row.get(key) is not None]
    if not values:
        return None
    return float(mean(values))


def rankdata(values: Sequence[float]) -> List[float]:
    order = sorted(range(len(values)), key=lambda idx: values[idx])
    ranks = [0.0] * len(values)
    i = 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and values[order[j + 1]] == values[order[i]]:
            j += 1
        avg_rank = (i + j + 2) / 2.0
        for k in range(i, j + 1):
            ranks[order[k]] = avg_rank
        i = j + 1
    return ranks


def spearman(rows: Sequence[Dict[str, object]], feature_key: str, target_key: str = "test_gain_vs_stage1") -> Optional[float]:
    pairs = [
        (float(row[feature_key]), float(row[target_key]))
        for row in rows
        if row.get(feature_key) is not None and row.get(target_key) is not None
    ]
    if len(pairs) < 3:
        return None
    xs = [item[0] for item in pairs]
    ys = [item[1] for item in pairs]
    rx = rankdata(xs)
    ry = rankdata(ys)
    mx = sum(rx) / len(rx)
    my = sum(ry) / len(ry)
    num = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    den_x = sum((a - mx) ** 2 for a in rx) ** 0.5
    den_y = sum((b - my) ** 2 for b in ry) ** 0.5
    if den_x == 0.0 or den_y == 0.0:
        return None
    return float(num / (den_x * den_y))


def summarize_subset(rows: Sequence[Dict[str, object]]) -> Dict[str, object]:
    total_test = sum(int(row["num_test"]) for row in rows)
    if total_test == 0:
        return {
            "num_relations": len(rows),
            "num_test": 0,
            "stage1_mrr": None,
            "stage2_mrr": None,
            "gain": None,
        }
    stage1 = sum(float(row["rule_stage_mrr"]) * int(row["num_test"]) for row in rows) / total_test
    stage2 = sum(float(row["final_mrr"]) * int(row["num_test"]) for row in rows) / total_test
    return {
        "num_relations": int(len(rows)),
        "num_test": int(total_test),
        "stage1_mrr": float(stage1),
        "stage2_mrr": float(stage2),
        "gain": float(stage2 - stage1),
    }


def zscore_stats(rows: Sequence[Dict[str, object]], key: str) -> Tuple[float, float]:
    values = [float(row[key]) for row in rows if row.get(key) is not None]
    mean_value = sum(values) / len(values)
    variance = sum((value - mean_value) ** 2 for value in values) / len(values)
    std_value = variance**0.5 or 1.0
    return float(mean_value), float(std_value)


def zscore(value: Optional[float], stats: Tuple[float, float]) -> float:
    if value is None:
        return -999.0
    mean_value, std_value = stats
    return (float(value) - mean_value) / std_value


def density_candidate_rankings(rows: Sequence[Dict[str, object]]) -> Dict[str, List[Dict[str, object]]]:
    stats = {
        key: zscore_stats(rows, key)
        for key in ["num_triples", "num_objects", "num_deps", "dep_per_rule", "avg_tails_per_sp", "num_rules"]
    }

    def score_support_dense(row: Dict[str, object]) -> float:
        return (
            zscore(row.get("num_triples"), stats["num_triples"])
            + zscore(row.get("num_objects"), stats["num_objects"])
            + zscore(row.get("num_deps"), stats["num_deps"])
            + zscore(row.get("dep_per_rule"), stats["dep_per_rule"])
            + zscore(row.get("num_rules"), stats["num_rules"])
        )

    def score_support_compact(row: Dict[str, object]) -> float:
        return score_support_dense(row) - zscore(row.get("avg_tails_per_sp"), stats["avg_tails_per_sp"])

    ranking_specs = {
        "top_train": lambda row: float(row.get("num_triples") or -1.0),
        "top_num_objects": lambda row: float(row.get("num_objects") or -1.0),
        "top_num_deps": lambda row: float(row.get("num_deps") or -1.0),
        "top_dep_per_rule": lambda row: float(row.get("dep_per_rule") or -1.0),
        "top_num_rules": lambda row: float(row.get("num_rules") or -1.0),
        "top_avg_tails": lambda row: float(row.get("avg_tails_per_sp") or -1.0),
        "low_avg_tails": lambda row: -(float(row.get("avg_tails_per_sp") or 999.0)),
        "score_support_dense": score_support_dense,
        "score_support_compact": score_support_compact,
    }
    return {
        name: sorted(rows, key=key_fn, reverse=True)
        for name, key_fn in ranking_specs.items()
    }


def find_oracle_topn(rows: Sequence[Dict[str, object]], overall_gain: float, total_test: int) -> Optional[Dict[str, object]]:
    ordered = sorted(rows, key=lambda row: float(row["test_gain_vs_stage1"]), reverse=True)
    coverage_thresholds = [0.05, 0.03, 0.02, 0.01, 0.0]
    for min_coverage in coverage_thresholds:
        min_weight = max(1, int(total_test * min_coverage))
        for n in range(1, len(ordered) + 1):
            subset = ordered[:n]
            summary = summarize_subset(subset)
            if summary["gain"] is None or summary["num_test"] < min_weight:
                continue
            if summary["gain"] >= 2.0 * overall_gain:
                return {
                    "subset_kind": "oracle_top_gain",
                    "ranking": "test_gain_vs_stage1 desc",
                    "min_coverage_required": float(min_coverage),
                    "topn": int(n),
                    "summary": summary,
                    "relations": subset,
                    "gain_ratio": float(summary["gain"] / overall_gain) if overall_gain else None,
                }
    return None


def find_best_density_topn(rows: Sequence[Dict[str, object]], overall_gain: float, total_test: int) -> Optional[Dict[str, object]]:
    best_candidate: Optional[Dict[str, object]] = None
    for ranking_name, ordered_rows in density_candidate_rankings(rows).items():
        for n in range(1, len(ordered_rows) + 1):
            subset = ordered_rows[:n]
            summary = summarize_subset(subset)
            if summary["gain"] is None:
                continue
            coverage = summary["num_test"] / total_test if total_test else 0.0
            if coverage < 0.05:
                continue
            gain_ratio = summary["gain"] / overall_gain if overall_gain else None
            candidate = {
                "subset_kind": "density_topn",
                "ranking": ranking_name,
                "topn": int(n),
                "summary": summary,
                "relations": subset,
                "gain_ratio": gain_ratio,
                "coverage": coverage,
            }
            if best_candidate is None:
                best_candidate = candidate
                continue
            current_key = (
                candidate["gain_ratio"] or float("-inf"),
                candidate["summary"]["gain"],
                candidate["coverage"],
                -candidate["topn"],
            )
            best_key = (
                best_candidate["gain_ratio"] or float("-inf"),
                best_candidate["summary"]["gain"],
                best_candidate["coverage"],
                -best_candidate["topn"],
            )
            if current_key > best_key:
                best_candidate = candidate
    return best_candidate


def subset_density_stats(subset_rows: Sequence[Dict[str, object]], all_rows: Sequence[Dict[str, object]]) -> Dict[str, Optional[float]]:
    return {
        "oracle_subset_avg_num_triples": average(subset_rows, "num_triples"),
        "all_avg_num_triples": average(all_rows, "num_triples"),
        "oracle_subset_avg_avg_tails_per_sp": average(subset_rows, "avg_tails_per_sp"),
        "all_avg_avg_tails_per_sp": average(all_rows, "avg_tails_per_sp"),
        "oracle_subset_avg_dep_per_rule": average(subset_rows, "dep_per_rule"),
        "all_avg_dep_per_rule": average(all_rows, "dep_per_rule"),
        "oracle_subset_avg_num_deps": average(subset_rows, "num_deps"),
        "all_avg_num_deps": average(all_rows, "num_deps"),
    }


def existing_subset_ratios(metrics_subset: Dict[str, object], overall_gain: float) -> Dict[str, Optional[float]]:
    ratios: Dict[str, Optional[float]] = {}
    for subset_name, payload in (metrics_subset.get("subsets") or {}).items():
        summary = (payload or {}).get("summary") if payload else None
        gain = None if summary is None else summary.get("gain_vs_stage1")
        ratios[subset_name] = None if gain is None or overall_gain == 0.0 else float(gain / overall_gain)
    return ratios


def write_csv(path: Path, rows: Sequence[Dict[str, object]], fieldnames: Sequence[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            out_row = {}
            for key in fieldnames:
                value = row.get(key)
                if isinstance(value, float):
                    out_row[key] = f"{value:.6f}"
                else:
                    out_row[key] = value
            writer.writerow(out_row)


def build_report(summary_rows: Sequence[Dict[str, object]], output_dir: Path) -> None:
    lines: List[str] = []
    lines.append("# Stage2 Gain Density Analysis")
    lines.append("")
    lines.append("结论基于每个数据集当前最优已完成配置，比较 `stage2 - stage1` 的关系级增益是否集中在更稠密的关系上。")
    lines.append("")
    lines.append("## 汇总表")
    lines.append("")
    lines.append("| Dataset | Best config | Overall gain | Oracle topN | Oracle ratio | Oracle coverage | Density topN | Density ratio | Density coverage |")
    lines.append("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for row in summary_rows:
        lines.append(
            "| {dataset} | {config} | {overall} | {oracle_n} | {oracle_ratio} | {oracle_cov} | {dense_n} | {dense_ratio} | {dense_cov} |".format(
                dataset=row["dataset"],
                config=row["best_config_label"].replace("|", "\\|"),
                overall=fmt_float(row["overall_gain"]),
                oracle_n=row["oracle_topn"] or "-",
                oracle_ratio=fmt_ratio(row["oracle_gain_ratio"]) or "-",
                oracle_cov=fmt_float(row["oracle_coverage"]),
                dense_n=row["density_topn"] or "-",
                dense_ratio=fmt_ratio(row["density_gain_ratio"]) or "-",
                dense_cov=fmt_float(row["density_coverage"]),
            )
        )
    lines.append("")

    lines.append("## 数据集逐项结论")
    lines.append("")
    for row in summary_rows:
        lines.append(f"### {row['dataset']}")
        lines.append("")
        lines.append(
            f"- 最优配置是 `{row['best_config_label']}`，整体 `stage2-stage1` MRR 增益为 `{fmt_float(row['overall_gain'])}`。"
        )
        lines.append(
            f"- 关系级 Spearman 相关：`train={fmt_float(row['spearman_num_triples'])}`，"
            f"`avg_tails={fmt_float(row['spearman_avg_tails_per_sp'])}`，"
            f"`dep_per_rule={fmt_float(row['spearman_dep_per_rule'])}`。"
        )
        if row["oracle_topn"]:
            lines.append(
                f"- Oracle 子集：按真实关系增益排序取前 `{row['oracle_topn']}` 个关系，"
                f"子集增益达到 `{fmt_float(row['oracle_gain'])}`，是整体的 `{fmt_ratio(row['oracle_gain_ratio'])}`，"
                f"覆盖测试集 `{fmt_float(row['oracle_coverage'])}`。"
            )
        else:
            lines.append("- Oracle 子集：在至少 1% 覆盖率下，没有找到能把整体增益翻倍的 topN 子集。")
        if row["density_topn"]:
            lines.append(
                f"- Density 子集：按 `{row['density_ranking']}` 排序取前 `{row['density_topn']}` 个关系，"
                f"子集增益为 `{fmt_float(row['density_gain'])}`，是整体的 `{fmt_ratio(row['density_gain_ratio'])}`，"
                f"覆盖测试集 `{fmt_float(row['density_coverage'])}`。"
            )
        else:
            lines.append("- Density 子集：没有找到满足 5% 测试覆盖率的有效 topN 候选。")
        lines.append(
            f"- Oracle 子集与全体关系相比：`avg(train)` {fmt_float(row['oracle_subset_avg_num_triples'])} vs {fmt_float(row['all_avg_num_triples'])}，"
            f"`avg(tails)` {fmt_float(row['oracle_subset_avg_avg_tails_per_sp'])} vs {fmt_float(row['all_avg_avg_tails_per_sp'])}，"
            f"`avg(dep/rule)` {fmt_float(row['oracle_subset_avg_dep_per_rule'])} vs {fmt_float(row['all_avg_dep_per_rule'])}。"
        )
        lines.append("")

    report_path = output_dir / "stage2_gain_density_report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    summary_path = Path(args.wide_summary)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rows_by_dataset = read_wide_summary(summary_path)
    summary_rows: List[Dict[str, object]] = []
    subsets_payload: Dict[str, object] = {}

    for dataset in DATASETS:
        best_row = best_completed_config(rows_by_dataset[dataset])
        metrics_subset_path = Path(best_row["experiment_dir"]) / "metrics-subset.json"
        metrics_subset = read_json(metrics_subset_path)
        relation_rows = metrics_subset["relation_rows"]
        overall_summary = metrics_subset["subsets"]["all_relations"]["summary"]
        overall_gain = float(overall_summary["gain_vs_stage1"])
        total_test = int(overall_summary["num_test"])

        oracle_topn = find_oracle_topn(relation_rows, overall_gain, total_test)
        density_topn = find_best_density_topn(relation_rows, overall_gain, total_test)
        subset_ratios = existing_subset_ratios(metrics_subset, overall_gain)

        positive_rows = [row for row in relation_rows if float(row["test_gain_vs_stage1"]) > 0.0]
        non_positive_rows = [row for row in relation_rows if float(row["test_gain_vs_stage1"]) <= 0.0]

        oracle_stats = subset_density_stats(oracle_topn["relations"], relation_rows) if oracle_topn else subset_density_stats([], relation_rows)

        summary_row: Dict[str, object] = {
            "dataset": dataset,
            "best_config_id": best_row["config_id"],
            "best_config_label": best_row["config_label"],
            "best_stage2_mrr": to_float(best_row["stage2_mrr"]),
            "overall_gain": overall_gain,
            "num_relations": len(relation_rows),
            "num_positive_gain_relations": len(positive_rows),
            "num_non_positive_gain_relations": len(non_positive_rows),
            "spearman_num_triples": spearman(relation_rows, "num_triples"),
            "spearman_num_objects": spearman(relation_rows, "num_objects"),
            "spearman_avg_tails_per_sp": spearman(relation_rows, "avg_tails_per_sp"),
            "spearman_num_rules": spearman(relation_rows, "num_rules"),
            "spearman_num_deps": spearman(relation_rows, "num_deps"),
            "spearman_dep_per_rule": spearman(relation_rows, "dep_per_rule"),
            "positive_avg_num_triples": average(positive_rows, "num_triples"),
            "non_positive_avg_num_triples": average(non_positive_rows, "num_triples"),
            "positive_avg_avg_tails_per_sp": average(positive_rows, "avg_tails_per_sp"),
            "non_positive_avg_avg_tails_per_sp": average(non_positive_rows, "avg_tails_per_sp"),
            "positive_avg_dep_per_rule": average(positive_rows, "dep_per_rule"),
            "non_positive_avg_dep_per_rule": average(non_positive_rows, "dep_per_rule"),
            "oracle_topn": None if oracle_topn is None else oracle_topn["topn"],
            "oracle_gain": None if oracle_topn is None else oracle_topn["summary"]["gain"],
            "oracle_gain_ratio": None if oracle_topn is None else oracle_topn["gain_ratio"],
            "oracle_coverage": None if oracle_topn is None else oracle_topn["summary"]["num_test"] / total_test,
            "oracle_min_coverage_required": None if oracle_topn is None else oracle_topn["min_coverage_required"],
            "density_ranking": None if density_topn is None else density_topn["ranking"],
            "density_topn": None if density_topn is None else density_topn["topn"],
            "density_gain": None if density_topn is None else density_topn["summary"]["gain"],
            "density_gain_ratio": None if density_topn is None else density_topn["gain_ratio"],
            "density_coverage": None if density_topn is None else density_topn["coverage"],
            "subset_ratio_dependency_friendly_train_only": subset_ratios.get("dependency_friendly_train_only"),
            "subset_ratio_dependency_friendly_moderate_dense": subset_ratios.get("dependency_friendly_moderate_dense"),
            "subset_ratio_dependency_friendly_high_dependency_dense": subset_ratios.get("dependency_friendly_high_dependency_dense"),
            "subset_ratio_dependency_friendly_static_union": subset_ratios.get("dependency_friendly_static_union"),
        }
        summary_row.update(oracle_stats)
        summary_rows.append(summary_row)

        subsets_payload[dataset] = {
            "dataset": dataset,
            "best_config": {
                "config_id": best_row["config_id"],
                "config_label": best_row["config_label"],
                "stage2_mrr": to_float(best_row["stage2_mrr"]),
                "overall_gain_vs_stage1": overall_gain,
            },
            "oracle_topn": None
            if oracle_topn is None
            else {
                "topn": oracle_topn["topn"],
                "gain": oracle_topn["summary"]["gain"],
                "gain_ratio": oracle_topn["gain_ratio"],
                "coverage": oracle_topn["summary"]["num_test"] / total_test,
                "ranking": oracle_topn["ranking"],
                "relations": [
                    {
                        "relation": int(row["relation"]),
                        "rel_name": row["rel_name"],
                        "num_test": int(row["num_test"]),
                        "num_triples": row.get("num_triples"),
                        "avg_tails_per_sp": row.get("avg_tails_per_sp"),
                        "dep_per_rule": row.get("dep_per_rule"),
                        "test_gain_vs_stage1": row.get("test_gain_vs_stage1"),
                    }
                    for row in oracle_topn["relations"]
                ],
            },
            "density_topn": None
            if density_topn is None
            else {
                "topn": density_topn["topn"],
                "gain": density_topn["summary"]["gain"],
                "gain_ratio": density_topn["gain_ratio"],
                "coverage": density_topn["coverage"],
                "ranking": density_topn["ranking"],
                "relations": [
                    {
                        "relation": int(row["relation"]),
                        "rel_name": row["rel_name"],
                        "num_test": int(row["num_test"]),
                        "num_triples": row.get("num_triples"),
                        "avg_tails_per_sp": row.get("avg_tails_per_sp"),
                        "dep_per_rule": row.get("dep_per_rule"),
                        "test_gain_vs_stage1": row.get("test_gain_vs_stage1"),
                    }
                    for row in density_topn["relations"]
                ],
            },
        }

    fieldnames = [
        "dataset",
        "best_config_id",
        "best_config_label",
        "best_stage2_mrr",
        "overall_gain",
        "num_relations",
        "num_positive_gain_relations",
        "num_non_positive_gain_relations",
        "spearman_num_triples",
        "spearman_num_objects",
        "spearman_avg_tails_per_sp",
        "spearman_num_rules",
        "spearman_num_deps",
        "spearman_dep_per_rule",
        "positive_avg_num_triples",
        "non_positive_avg_num_triples",
        "positive_avg_avg_tails_per_sp",
        "non_positive_avg_avg_tails_per_sp",
        "positive_avg_dep_per_rule",
        "non_positive_avg_dep_per_rule",
        "oracle_topn",
        "oracle_gain",
        "oracle_gain_ratio",
        "oracle_coverage",
        "oracle_min_coverage_required",
        "density_ranking",
        "density_topn",
        "density_gain",
        "density_gain_ratio",
        "density_coverage",
        "subset_ratio_dependency_friendly_train_only",
        "subset_ratio_dependency_friendly_moderate_dense",
        "subset_ratio_dependency_friendly_high_dependency_dense",
        "subset_ratio_dependency_friendly_static_union",
        "oracle_subset_avg_num_triples",
        "all_avg_num_triples",
        "oracle_subset_avg_avg_tails_per_sp",
        "all_avg_avg_tails_per_sp",
        "oracle_subset_avg_dep_per_rule",
        "all_avg_dep_per_rule",
        "oracle_subset_avg_num_deps",
        "all_avg_num_deps",
    ]
    write_csv(output_dir / "stage2_gain_density_summary.csv", summary_rows, fieldnames)
    (output_dir / "stage2_gain_topn_subsets.json").write_text(
        json.dumps(subsets_payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    build_report(summary_rows, output_dir)

    print(f"Wrote {output_dir / 'stage2_gain_density_summary.csv'}")
    print(f"Wrote {output_dir / 'stage2_gain_topn_subsets.json'}")
    print(f"Wrote {output_dir / 'stage2_gain_density_report.md'}")


if __name__ == "__main__":
    main()
